import { createServerClient } from '@supabase/ssr'
import type { NextRequest } from 'next/server'

/**
 * Verify the incoming request carries a valid Supabase session.
 * Uses getUser() (server round-trip) instead of getSession() so the token
 * is revalidated against the Supabase Auth server on every call.
 * Returns { id } for an authenticated user, null otherwise.
 */
export async function getRequestUser(req: NextRequest): Promise<{ id: string } | null> {
  try {
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          get(name: string) {
            return req.cookies.get(name)?.value
          },
          // POST handlers don't need to refresh tokens; no-ops are fine here.
          set() {},
          remove() {},
        },
      }
    )
    const {
      data: { user },
    } = await supabase.auth.getUser()
    return user ? { id: user.id } : null
  } catch {
    return null
  }
}

/**
 * SSRF guard: only allow fetching images that live in THIS project's
 * Supabase Storage public artworks bucket.
 *
 * Accepted form:
 *   https://<project>.supabase.co/storage/v1/object/public/artworks/...
 */
export function isAllowedImageUrl(imageUrl: string): boolean {
  try {
    const supabaseBase = process.env.NEXT_PUBLIC_SUPABASE_URL
    if (!supabaseBase) return false

    const parsed = new URL(imageUrl)
    const base = new URL(supabaseBase)

    return (
      parsed.protocol === 'https:' &&
      parsed.host === base.host &&
      parsed.pathname.startsWith('/storage/v1/object/public/artworks/') &&
      parsed.username === '' &&
      parsed.password === ''
    )
  } catch {
    return false
  }
}

/**
 * Path-injection guard: baseFileName is generated by the client as
 * `${Date.now()}-${Math.random().toString(36).slice(2,10)}`
 * e.g. "1719400123456-g7hk2m9q"
 *
 * Only allow that exact shape — no slashes, dots, or other traversal chars.
 */
export function isValidBaseFileName(name: string): boolean {
  return /^\d{10,16}-[a-z0-9]{4,16}$/.test(name)
}
